#!/bin/bash

read -p "Number of Subspace:" q
echo -e "Your Number of Subspace: ${q}"
h=$[q-1]
read -p "Operating Frequency(MHz):" w
echo -e "Your Operating Frequency(MHz): ${w}" 
read -p "delta of incident wave:" y
echo -e "delta of incident wave: ${y}"
d=$[y]
r="((180/d)+1)*((360/d)+1)-1"
mkdir apMulti
for ((p=0;p<=r;p++))
do
	mkdir apMulti/ang$p
	
	cp fast_n2f angle$p
	cd angle$p
		for ((i=0;i<=h;i++))

		do

			cp fast_n2f $i

			cd $i

			./fast_n2f $i $w 180 360	  

			cd ..

			cd ..

			cp angle$p/$i/$i.ap apMulti/ang$p
	
			cd apMulti/ang$p 

			sed -i '1d' $i.ap
	
			cd ..
			
			cd ..	

			cd angle$p
		done
	cd ..
done

